services:
  web:
    image: dev_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/user/app
      - ./logs/web:/home/user/app/logs
      - ./media:/home/user/app/media
    # command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    command:
      - make
      - migrate
      - runserver
    ports:
      - 8000:8000
    env_file:
      - .env
      - .env.docker
    environment:
      - BROKER_URL=redis://cache
      - MEDIA_ROOT=/home/user/app/media
      - LOGS_ROOT=/home/user/app/logs
      - DJANGO_WEB_HOST="web"
    links:
      - redis:cache
    networks:
      - backend

  worker:
    image: dev_worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/user/app
      - ./logs/worker:/home/user/app/logs
      - ./media:/home/user/app/media
    # command: python manage.py celery_autoreload
    command:
      - make
      - celery
    env_file:
      - .env
      - .env.docker
    environment:
      - BROKER_URL=redis://cache
      - MEDIA_ROOT=/home/user/app/media
      - LOGS_ROOT=/home/user/app/logs
    links:
      - redis:cache
    networks:
      - backend
    depends_on:
      redis:
        condition: service_started
      web:
        condition: service_started

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - backend

networks:
  backend:
    driver: bridge